version: "3" # 버전
services:
  # 띄울 컨테이너들을 들여쓰기로 구분
  react:
    # 첫 번째 컨테이너 이름
    build:
      # 빌드 옵션들
      context: . # 도커 파일의 위치
      dockerfile: Dockerfile # 도커파일 이름
    ports:
      # 포트 옵션
      - "80:80" # 매핑할 포트 이름
    volumes:
      # 볼륨 옵션
      - /usr/src/app/node_modules # node_modules 폴더는 호스트에 없기 떄문에 참조하지 않고 컨테이너에서 npm install 커맨드로 생성한다.
      - ./:/usr/src/app # node_modules 제외한 나머지는 호스트에서 참조한다.
    # stdin_open: true 는
    # docker run -it 에서
    # -i 의 역할이다.
    stdin_open: true