# Generated by Django 3.2.13 on 2022-10-06 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='dummy.png', upload_to='')),
                ('title', models.CharField(max_length=30)),
                ('summary', models.TextField()),
                ('running_time', models.IntegerField()),
                ('director', models.TextField()),
                ('release', models.DateField()),
                ('total_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('avg_score', models.IntegerField(default=0)),
                ('vote_cnt', models.IntegerField(default=0)),
            ],
        ),
    ]
